

function setup(){
    draw();
    frameRate(0.1);
}

function draw(){
    var b = new Beetle(-1,-1,Array(),Array());
    var cropped = trimCanvas(b.canvas.canvas);
    b.canvas.remove();
        
    var bimg = document.getElementById('beetleimg');
    bimg.innerHTML = '';
    bimg.appendChild(cropped);
    cropped.id = 'beetlecanvas';
    cropped.style.display = 'block';
        
    document.getElementById('beetle').style.backgroundImage = 'url(' + b.bg.canvas.toDataURL() + ')';
    b.bg.remove();
    
    var texts = Array(2);
    texts = [
        "All beetles are generated by one algorithm.",
        "All beetles only consist of points and curves.",
        "Attributes: "+b.name,
        "There are 3 different types of feeler ends.",
        "There are 3 different types of wing pattern.",
        "Each bug has two main colors.",
        "More than 50 parameters can be changed.",
        "You can print them on t-shirts ;)",
        "Follow @beetlesbot on Twitter!",
        "Follow @beetlesbot on Mastodon!",
        "Millions of different beetles are possible!",
        "Make your own: beetles. bleeptrack.de"
    ];
    
    var t = document.getElementById('text');
    t.innerHTML = '<p>'+texts[b.rndHidden(0,texts.length-1)]+'</p>';
    t.style.color = b.wingsC2;
    var bcol = b.wingsC1;
    //t.style.webkitTextStroke = "1px "+bcol;
    t.style.textShadow = "4px 4px 0 "+bcol+", 3px 3px 0 "+bcol+", 2px 2px 0 "+bcol+", 1px -1px 0 "+bcol;
    
    //makeQR(b);
    
    
}

function makeQR(bug){
    var qrcode = new QRCode("text", {
        text: "http://beetles.bleeptrack.de",
        width: 700,
        height: 700,
        colorDark : "#000000",
        colorLight : "#ffffff",
        correctLevel : QRCode.CorrectLevel.H
    });
}
